### ISSUE TITLE
npm ERR! 404  '@samverschueren/stream-to-observable@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by JhonMyHW** [SamVerschueren/stream-to-observable#6]
Hi Sam!

I'm having issues while trying to install your package.

Jonathan:testing jonathan$ npm install --save @samverschueren/stream-to-observable
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@samverschueren%2fstream-to-observable - Not found
npm ERR! 404 
npm ERR! 404  '@samverschueren/stream-to-observable@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathan/.npm/_logs/2020-08-06T09_51_18_924Z-debug.log

I was able to do it before. Any issues spotted lately?

Thanks!

**Comment by bengry** [comment]
Getting the same thing, and seeing it as a 503, at least when trying to use an npm token as part of a `yarn install`.

**Comment by Avonavi232** [comment]
Seeing this as same as TS do

**Comment by oswaldoacauan** [comment]
~@SamVerschueren can you publish the package again?~

ok seems like the issue is at @npm

**Comment by Avonavi232** [comment]
see
https://github.com/npm/cli/issues/1626
https://github.com/npm/cli/issues/1624

and others

**Comment by JhonMyHW** [comment]
Yeah, seems a global issue with NPM affecting all package installs.
They had an outage a couple of hours ago.

You can keep the track of the issue here:
https://status.npmjs.org/

Thanks everyone for your help and fast feedback!
